services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: looton
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
