name: Build and Publish Backend Docker Image

on:
  push:
    paths:
      - 'looton/backend/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: looton/backend
          file: looton/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/looton-backend:latest
            ghcr.io/${{ github.repository_owner }}/looton-backend:${{ github.sha }}

      - name: Output image
        run: |
          echo "Image pushed: ghcr.io/${{ github.repository_owner }}/looton-backend:latest"
